export const AC_TEMP_CHANGE = 'AC_TEM_CHANGE';
export const AC_MODE_CHANGE = 'AC_MODE_CHANGE';
export const AC_WIND_SPEED_CHANGE = 'AC_WIND_SPEED_CHANGE';
export const AC_WIND_DIRECTION_CHANGE = 'AC_WIND_DIRECTION_CHANGE';
export const AC_SWITCH = 'AC_SWITCH';
